### ISSUE TITLE
Dockerfile build的镜像pier运行问题

### ISSUE THREAD

**Issue by seanachao** [meshplus/pier#103]
## pier不能运行的问题
当使用master分支v1.1.0-rc1 的dockerfile build镜像后,run镜像后，使用命令报错
![image](https://user-images.githubusercontent.com/30539692/95953487-72110500-0e2c-11eb-85ca-d9091c458eb1.png)
```
~ # pier --repo=/root/.pier appchain register --name=${APPCHAIN_NAME} --type=fabric --validators=/root/.pier/${PLUGIN_CONFIG}/fabric.validators --desc="appchain for test" --version=1.4.3
invoke bvm contract: send tx error: failed to retrieve account nonce: rpc error: code = Unimplemented desc = unknown method GetPendingNonceByAccount for service pb.ChainBroker

```

**Comment by Alexader** [comment]
GetPendingNonceByAccount method is added in release 1.3, are you sure you have checkouted to the right version v1.1.0-rc1 and run the `docker build`?
