### ISSUE TITLE
应用链注册报错

### ISSUE THREAD

**Issue by bolenzhang** [meshplus/pier#111]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?
按手册操作，v1.0.0版本：
pier appchain register --key=~/goproj/src/github.com/meshplus/.pier/key.json --name=fab --type=fabric --validators=$HOME/.pier/fabric/fabric.validators --desc="fabric appchain for test" --version=1.4.3

### 2. What did you expect to see?
正常注册
### 3. What did you see instead?
flag provided but not defined: --key
### 4. What version of BitXHub are you using? (`bitxhub version` on BitXHub)
v1.0.0-rc1

**Comment by Alexader** [comment]
The command used to register appchain is not the newest. Please try `pier --repo ~/goproj/src/github.com/meshplus/.pier appchain register --name=fab --type=fabric --validators=$HOME/.pier/fabric/fabric.validators --desc="fabric appchain for test" --version=1.4.3` instead.
We have updated our wiki, and thank you for your issue report.
