### ISSUE TITLE
网关执行应用链注册操作报错

### ISSUE THREAD

**Issue by iamlijinhui** [meshplus/pier#368]
## General Question
pier --repo ./ appchain register --appchain-id "appchain1" --name "fabric1" --type "Fabric V1.4.3" --trustroot $HOME/.goduck/pier/.pier_fabric/fabric/fabric.validators --broker-cid mychanncel --broker-ccid broker --broker-v 1 --desc "desc" --master-rule "0x00000000000000000000000000000000000000a2" --rule-url "http://github.com" --admin 0x02E2De5aF4E06fC74D2EB34B87539F6fD57d777D --reason "reason"

报错如下：
panic: invalid Go type *types.Address for field pb.BxhTransaction.from

goroutine 1 [running]:
google.golang.org/protobuf/internal/impl.newSingularConverter(0x219d0c0, 0x1e58920, 0x219d540, 0xc00023b8f0, 0x8, 0xc0004a0b20)
        /home/runner/go/pkg/mod/google.golang.org/protobuf@v1.26.0/internal/impl/convert.go:143 +0xf17
google.golang.org/protobuf/internal/impl.NewConverter(0x219d0c0, 0x1e58920, 0x219d540, 0xc00023b8f0, 0x203000, 0x203000)
        /home/runner/go/pkg/mod/google.golang.org/protobuf@v1.26.0/internal/impl/convert.go:60 +0xdc

**Comment by jgr-great** [comment]
同学部署成功了么，交流一下呀

**Comment by iamlijinhui** [comment]
可以跨链，但很多功能不可用



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月2日(星期四) 中午11:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [meshplus/pier] 网关执行应用链注册操作报错 (Issue #368)





 
同学部署成功了么，交流一下呀

**Comment by jgr-great** [comment]
fabric和ethereum可以跨么，网关注册那一步我就卡住了。。。。应该得看代码才行
| |
姜国仁
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年03月2日 14:20 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [meshplus/pier] 网关执行应用链注册操作报错 (Issue #368) |

可以跨链，但很多功能不可用



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;;
发送时间: 2023年3月2日(星期四) 中午11:26
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;; ***@***.***&gt;;
主题: Re: [meshplus/pier] 网关执行应用链注册操作报错 (Issue #368)






同学部署成功了么，交流一下呀

**Comment by iamlijinhui** [comment]
可以，大部分都是环境问题

**Comment by jgr-great** [comment]
你用的是哪个版本，我跟着官方文档用的1.6.0版本，网关注册fabric链的时候报错，


命令
pier --repo ./.pier appchain register --name=chainA --type=fabric --validators=./.pier/fabric/fabric.validators --desc="fabric appchain for test" --version=1.4.3



报错
INFO[14:36:32.784] Establish connection with bitxhub localhost:60011 successfully  module=rpcx
invoke bvm contract: send tx error: failed to retrieve account nonce: rpc error: code = Unimplemented desc = unknown method GetPendingNonceByAccount for service pb.ChainBroker, broken network



这种你遇到过么，感觉不像环境问题


| |
姜国仁
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年03月2日 14:36 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [meshplus/pier] 网关执行应用链注册操作报错 (Issue #368) |

可以，大部分都是环境问题

**Comment by iamlijinhui** [comment]
我觉得应该是部署跨链网关的时候有的配置没弄好

**Comment by iamlijinhui** [comment]
我没遇到过这个问题

**Comment by Karenlrx** [comment]
> 

请提供pier与bitxhub的版本，以上问题出现大多是网关与中继链版本不一致导致的。具体跨链部署教程参考最新的[文档站](https://docs.bitxhub.cn/v2.8/bitxhub/quick_start/build_cross_network/overall_description/)

**Comment by Karenlrx** [comment]
> 

你好，可能是pier的grpc版本的问题导致的。此外，1.6版本已经非常久远了，可能存在一些遗留问题，如果要体验跨链流程可以参考最新[文档站](https://docs.bitxhub.cn/v2.8/bitxhub/quick_start/build_cross_network/overall_description/)。

**Comment by Karenlrx** [comment]
> 你用的是哪个版本，我跟着官方文档用的1.6.0版本，网关注册fabric链的时候报错， 命令 pier --repo ./.pier appchain register --name=chainA --type=fabric --validators=./.pier/fabric/fabric.validators --desc="fabric appchain for test" --version=1.4.3 报错 INFO[14:36:32.784] Establish connection with bitxhub localhost:60011 successfully module=rpcx invoke bvm contract: send tx error: failed to retrieve account nonce: rpc error: code = Unimplemented desc = unknown method GetPendingNonceByAccount for service pb.ChainBroker, broken network 这种你遇到过么，感觉不像环境问题

你好，可能是pier的grpc版本的问题导致的。此外，1.6版本已经非常久远了，可能存在一些遗留问题，如果要体验跨链流程可以参考最新[文档站](https://docs.bitxhub.cn/v2.8/bitxhub/quick_start/build_cross_network/overall_description/)。

**Comment by Karenlrx** [comment]
> ## General Question
> pier --repo ./ appchain register --appchain-id "appchain1" --name "fabric1" --type "Fabric V1.4.3" --trustroot $HOME/.goduck/pier/.pier_fabric/fabric/fabric.validators --broker-cid mychanncel --broker-ccid broker --broker-v 1 --desc "desc" --master-rule "0x00000000000000000000000000000000000000a2" --rule-url "[http://github.com](https://github.com)" --admin 0x02E2De5aF4E06fC74D2EB34B87539F6fD57d777D --reason "reason"
> 
> 报错如下： panic: invalid Go type *types.Address for field pb.BxhTransaction.from
> 
> goroutine 1 [running]: google.golang.org/protobuf/internal/impl.newSingularConverter(0x219d0c0, 0x1e58920, 0x219d540, 0xc00023b8f0, 0x8, 0xc0004a0b20) /home/runner/go/pkg/mod/google.golang.org/protobuf@v1.26.0/internal/impl/convert.go:143 +0xf17 google.golang.org/protobuf/internal/impl.NewConverter(0x219d0c0, 0x1e58920, 0x219d540, 0xc00023b8f0, 0x203000, 0x203000) /home/runner/go/pkg/mod/google.golang.org/protobuf@v1.26.0/internal/impl/convert.go:60 +0xdc

请提供pier与bitxhub的版本，以上问题出现大多是网关与中继链版本不一致导致的。具体跨链部署教程参考最新的[文档站](https://docs.bitxhub.cn/v2.8/bitxhub/quick_start/build_cross_network/overall_description/)

**Comment by jgr-great** [comment]
你好

我所有组件都使用的是2.8.0版本，但是fabric合约部署遇到了问题：使用1.4.3版本的fabric合约部署有问题；使用2.2.6版本合约能够部署，但是pier-client-fabric网关用的fabric sdk版本跟fabric不兼容。

我应该使用哪个版本的fabric，还有ccenv用哪个版本。

谢谢

**Comment by jgr-great** [comment]
使用2.2.6版本的fabric时，sdk报这个错误new appchain adapter: initialize plugin /root/pier_fabric/fabric: rpc error: code = Unknown desc = create channel fabcli fail: failed to create channel context: failed to get client context to create channel client: getting private key from cert failed: Failed getting key for SKI [[181 179 83 91 152 66 232 94 214 191 76 222 186 208 163 72 150 142 125 62 182 162 26 188 145 252 206 177 196 61 120 128]]: Key with SKI 
b5b3535b9842e85ed6bf4cdebad0a348968e7d3eb6a21abc91fcceb1c43d7880 not found in keystore

fabric 2.2.6 samples生成的证书私钥是priv_sk格式命名，但是sdk是以证书的ski找私钥

**Comment by jgr-great** [comment]
同学，我在注册服务的出现提示无权限的情况，可以帮忙看看么，具体issue #393
