### ISSUE TITLE
注册服务时提示没有管理员，无权限。请教一下这是什么原因

### ISSUE THREAD

**Issue by jgr-great** [meshplus/pier#393]
## General Question
我在部署合约的时候，已经设置了管理员，
### Command
pier --repo /root/pier_ether  appchain service register --appchain-id "ethappchain1" --service-id "0xf3bC07C161aC5198844C85EaF9D31Be7bef33D24" --name "ethServer" --intro "" --type CallContract --permit "" --details "test" --reason "reason" --ordered 1
### 错误提示
Error
```
register service info faild: call error: 1060001:regulatorAddr(0x8E8Cdd1DD64d4453b66d18154BE71706Bd53707d) does not have the permission: cross invoke GetAppchainAdmin error:2000000:call error: 1040013:there is no admin for the appchain(ethappchain1)
```

### broker合约参数
```
ethappchain1
["0xc7F999b83Af6DF9e67d0a37Ee7e900bF38b3D013","0x79a1215469FaB6f9c63c1816b45183AD3624bE34","0x97c8B516D19edBf575D72a172Af7F418BE498C37","0xc0Ff2e0b3189132D815b8eb325bE17285AC898f8"]
1
["0x4bff341fc1c9beb0869099f49b9151d11a0cddf6"]
1
0xA6985BCE4A6A1fB80192444F585f5977cD219C34
```

BitxHub的配置使用的是默认的
![image](https://user-images.githubusercontent.com/26888518/222704020-f4d39813-c333-4cf9-b90c-015069a97f6d.png)

**Comment by Karenlrx** [comment]
你是否提前注册了应用链？  在注册服务之前需要注册应用链，并且该提案需要投票并通过，注册应用链才会生效。注册应用链请参考：[注册应用链](https://docs.bitxhub.cn/v2.8/bitxhub/quick_start/build_cross_network/single_bitxhub/register_appchain/)

**Comment by Karenlrx** [comment]
> 

注册应用链并投票成功后，再进行应用链服务注册，同样的，注册操作是管理员发起一个提案，仍然需要各中继链管理员进行投票，如果是测试环境下，可以通过更改中继链的bitxhub.toml的投票策略来忽略投票这一步，即 简单多数投票策略（SimpleMajority）变更为0投票策略（ZeroPermission）
[[genesis.strategy]]
    module = "node_mgr"
    typ = "ZeroPermission"

**Comment by Karenlrx** [comment]
> ## General Question
> 我在部署合约的时候，已经设置了管理员，
> 
> ### Command
> pier --repo /root/pier_ether appchain service register --appchain-id "ethappchain1" --service-id "0xf3bC07C161aC5198844C85EaF9D31Be7bef33D24" --name "ethServer" --intro "" --type CallContract --permit "" --details "test" --reason "reason" --ordered 1
> 
> ### 错误提示
> Error
> 
> ```
> register service info faild: call error: 1060001:regulatorAddr(0x8E8Cdd1DD64d4453b66d18154BE71706Bd53707d) does not have the permission: cross invoke GetAppchainAdmin error:2000000:call error: 1040013:there is no admin for the appchain(ethappchain1)
> ```
> 
> ### broker合约参数
> ```
> ethappchain1
> ["0xc7F999b83Af6DF9e67d0a37Ee7e900bF38b3D013","0x79a1215469FaB6f9c63c1816b45183AD3624bE34","0x97c8B516D19edBf575D72a172Af7F418BE498C37","0xc0Ff2e0b3189132D815b8eb325bE17285AC898f8"]
> 1
> ["0x4bff341fc1c9beb0869099f49b9151d11a0cddf6"]
> 1
> 0xA6985BCE4A6A1fB80192444F585f5977cD219C34
> ```
> 
> BitxHub的配置使用的是默认的 ![image](https://user-images.githubusercontent.com/26888518/222704020-f4d39813-c333-4cf9-b90c-015069a97f6d.png)

需要注意的是，每一个genesis.strategy都需要更改，更改完毕后保存并重启中继链各节点即可，如果使用的make cluster启动，只需要更改项目下的config/bitxhub/toml即可，如果是每个节点自定义了repo路径，需要同步更改每个节点下的bitxhub.toml

**Comment by jgr-great** [comment]
非常感谢，已经部署成功了，但是从fabric到以太坊转账失败 ，以太坊到fabric转账成功.

错误信息：
ERRO[2023-03-08T11:05:01.734] Receipt result for ibtp                       fields.msg="call error: 1080013:index already exists, required 2, but 1" ibtp_id="1356:fabappchain:mychannel&transfer-1356:ethappchain1:0xBB0Cc277b3eE225202a567997525d189DE5D646d-1" ibtp_type=INTERCHAIN module=bxh_adapter

**Comment by jgr-great** [comment]
总是有这个错误，但是跨链成功

ERRO[2023-03-09T10:39:54.902] send IBTP to Adapt:appchain:ethappchain1%!(EXTRA string=error, string=fail to send ibtp 1356:ethappchain1:0xBB0Cc277b3eE225202a567997525d189DE5D646d-1356:fabappchain:mychannel&transfer-4 with type RECEIPT_SUCCESS: failed to estimate gas needed: execution reverted)  module=exchanger

**Comment by Karenlrx** [comment]
> 总是有这个错误，但是跨链成功
> 
> ERRO[2023-03-09T10:39:54.902] send IBTP to Adapt:appchain:ethappchain1%!(EXTRA string=error, string=fail to send ibtp 1356:ethappchain1:0xBB0Cc277b3eE225202a567997525d189DE5D646d-1356:fabappchain:mychannel&transfer-4 with type RECEIPT_SUCCESS: failed to estimate gas needed: execution reverted) module=exchanger

请问你用的什么版本的fabric插件（pier-client-fabric版本），以及对应的pier、bitxhub版本

**Comment by jgr-great** [comment]
全部是v2.8.0版本


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年03月14日 09:43 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [meshplus/pier] 注册服务时提示没有管理员，无权限。请教一下这是什么原因 (Issue #393) |

总是有这个错误，但是跨链成功

ERRO[2023-03-09T10:39:54.902] send IBTP to Adapt:appchain:ethappchain1%!(EXTRA string=error, string=fail to send ibtp 1356:ethappchain1:0xBB0Cc277b3eE225202a567997525d189DE5D646d-1356:fabappchain:mychannel&transfer-4 with type RECEIPT_SUCCESS: failed to estimate gas needed: execution reverted) module=exchanger

请问你用的什么版本的fabric插件（pier-client-fabric版本），以及对应的pier、bitxhub版本

**Comment by jgr-great** [comment]
@Karenlrx 你好，可能是由于我将ethereum的合约的_VALIDATORS设置为空，导致事务回滚
