### ISSUE TITLE
register pier to bitxhub error

### ISSUE THREAD

**Issue by tianyinoo** [meshplus/pier#99]
when I follow the guidance of quickly start doc to register pier to bitxhub, there is a error:
invoke bvm contract: rpc error code=unknownn desc = not found in DB

I see the code achieving  register cmd function, but I can't find where the error is

**Comment by Alexader** [comment]
Are you working the same release of pier and bitxhub? This error occurs because the tx for registeration haven't been processed by bitxhub. Maybe you should check the version of bitxhub and pier first.

**Comment by tianyinoo** [comment]
Thanks for your answer. I try to restart the bitxhub, then it's ok.
